{
	"version": 1627798446,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"buttarget-sheet0.png",
		"pro-sheet0.png",
		"info-sheet0.png",
		"bg1-sheet0.png",
		"bg3-sheet0.png",
		"bg2-sheet0.png",
		"back-sheet0.png",
		"back-sheet1.png",
		"addcash-sheet0.png",
		"panel-sheet0.png",
		"sprite3-sheet0.png",
		"sprite2-sheet0.png",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"SweetAlert.css",
		"SweetAlert.js"
	]
}